#!/bin/bash

# Downloads a local copy of qemu on docker-hub build machines
curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .

# Downloads the docker-xbuild script
curl -L https://raw.githubusercontent.com/davesilva/docker-xbuild/master/bin/build > docker-xbuild
chmod +x docker-xbuild
